sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t vinit003/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true vinit003/react-test npm test

after_success:
  - docker build -t vinit003/multi-client ./client
  - docker build -t vinit003/multi-nginx ./nginx
  - docker build -t vinit003/multi-server ./server
  - docker build -t vinit003/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push vinit003/multi-client
  - docker push vinit003/multi-nginx
  - docker push vinit003/multi-server
  - docker push vinit003/multi-worker

deploy:
  provider: "elasticbeanstalk"
  region: "ap-south-1"
  app: "muti-docker"
  env: "Muti-docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-767397890053"
  bucket_path: "multi-docker"
  on:
    branch: "main"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"